### ISSUE TITLE
Support mobiles

### ISSUE THREAD

**Issue by p16i** [codeforthailand/parliament-listening#13]
Related to #2
we haven't tested yet how this website looks like on mobiles. It would be good if we could support those devices.

**Comment by unnawut** [comment]
Do we have a design? Or up to us?

**Comment by p16i** [comment]
no design so far, but this should be straightforward as almost DOMs are full-width.

This section is probably the most difficult one. 

<img width="942" alt="image" src="https://user-images.githubusercontent.com/1214890/62640221-4f9f7400-b96b-11e9-8bdb-cac0d5518393.png">

We might make each subsection becomes full-with if we're on mobile. What do you think?
